### ISSUE TITLE
tap in app

### ISSUE THREAD

**Issue by Frozenelo** [pyclashbot/pymemuc#170]
why this is not tapping 

from pymemuc import PyMemuc
import time
memuc = PyMemuc()
memuc.start_vm(4)
memuc.get_adb_connection(vm_index=4)
memuc.start_app_vm(package_name='app name',vm_index=4)

command = 'adb shell input tap 730 290'
response = memuc.send_adb_command_vm(command=command,vm_index=4)
print("response ADB:", response)
memuc.send_adb_command_vm(command=command, vm_index=4)

i get response adb connected

**Comment by martinmiglio** [comment]
To use `PyMemuc.send_adb_command_vm`, the command does not need to include `adb` at the start. You should use `shell input tap 730 290` as your command argument.

This is because this binding only allows for calls to the adb executable and not the shell directly.
