### ISSUE TITLE
start_app_vm not work ?

### ISSUE THREAD

**Issue by Romhast** [pyclashbot/pymemuc#78]
Even if I enter an empty or incorrect package_name, it appears as true and does not work.

```
# import the PyMemuc class
from pymemuc import PyMemuc

# create a PyMemuc instance, doing so will automatically link to the MEMUC executable
memuc = PyMemuc()


print(memuc.start_app_vm( vm_index=0, package_name=" "))
```

**output allways: True**

**Comment by martinmiglio** [comment]
This does seem to be an unintended functionality, an exception should be raised if the command fails to start the app.

Can you try initializing the `PyMemuc` class with `debug=True` parameter, and then calling `start_app_vm`? This will output the call to the memuc executable which you can then run in a command prompt or shell. Share the outputs here.

**Comment by Romhast** [comment]
> This does seem to be an unintended functionality, an exception should be raised if the command fails to start the app.
> 
```
> Can you try initializing the `PyMemuc` class with `debug=True` parameter, and then calling `start_app_vm`? This will output the call to the memuc executable which you can then run in a command prompt or shell. Share the outputs here.

Hello, thank you for the answer, everything seems fine in the output, but it does not start :D

2023-11-16 23:34:40,939 - pymemuc.pymemuc - DEBUG - PyMemuc: Debug mode enabled
2023-11-16 23:34:40,939 - pymemuc.pymemuc - DEBUG - pymemuc._memuc.memuc_run:
2023-11-16 23:34:40,939 - pymemuc.pymemuc - DEBUG - 	Command: "D:\Program Files\Microvirt\Memu\memuc.exe -i 0 start"
2023-11-16 23:34:41,998 - pymemuc.pymemuc - DEBUG - 	Output: SUCCESS: start vm finished.
2023-11-16 23:34:41,998 - pymemuc.pymemuc - DEBUG - pymemuc._memuc.memuc_run:
2023-11-16 23:34:41,998 - pymemuc.pymemuc - DEBUG - 	Command: "D:\Program Files\Microvirt\Memu\memuc.exe -i 0 startapp WhatsApp"
2023-11-16 23:34:42,104 - pymemuc.pymemuc - DEBUG - 	Output: SUCCESS: start app finished.
```

**Comment by martinmiglio** [comment]
I see the issue, the package_name needs to be the full android package name, which you can list out using `get_app_info_list_vm`, should be something like `com.whatsapp`.

`memuc.exe` isn't very clear in its responses to certain commands, in this case it does state that the command was successful, so `pymemuc` has no way of knowing it was actually unsuccessful.

**Comment by Romhast** [comment]
> I see the issue, the package_name needs to be the full android package name, which you can list out using `get_app_info_list_vm`, should be something like `com.whatsapp`.
> 
> `memuc.exe` isn't very clear in its responses to certain commands, in this case it does state that the command was successful, so `pymemuc` has no way of knowing it was actually unsuccessful.

Yes it worked, the following output is only **com.whatsapp**
I learned that the section will be used. If you write this in the documents, it will be useful for everyone.

**['com.whatsapp-WhatsApp-232422001-2.23.24.22']**

**Comment by martinmiglio** [comment]
Thanks for the suggestion, I will update the documentation 👍

**Comment by martinmiglio** [comment]
Updated documentation: https://pymemuc.pyclashbot.app/en/latest/pymemuc.html#pymemuc.pymemuc.PyMemuc.start_app_vm
