### ISSUE TITLE
Locate UI elements

### ISSUE THREAD

**Issue by drutkoowski** [pyclashbot/pymemuc#79]
Hello.

I have seen the previous issue but they are not very helpful. Is there a possibility to show only the Memu (i.e. emulator) screen or run it in headless mode?
How can you optimally manage what is in the UI? (I have seen ui_dump = memuc.send_adb_command_vm(command="shell uiautomator dump", vm_index=index), but it returns a string and not the UI) and I would like to check the UI using XPATH (as in selenium).

**Comment by martinmiglio** [comment]
To run the machine in a headless mode, you can set the option when you call start vm, see [the documentation for `start_vm`](https://pymemuc.pyclashbot.app/en/latest/pymemuc.html#pymemuc.pymemuc.PyMemuc.start_vm).

As far as finding UI elements, there isn't a pre-made solution for `pymemuc`, but anything that can run over ADB can be used with this library.

**Comment by drutkoowski** [comment]
Thanks for following up. Actually I have seen that there is an option in docs to pass headless flag, but it raises an error. 
`RuntimeError: TypeError: create_vm() got an unexpected keyword argument 'headless'`
I am using the latest version - pymemuc==0.5.0

Regarding UI location, could you confirm that this is the best way to grab the layout?:
    memuc.send_adb_command_vm(command="adb -s shell uiautomator dump /sdcard/view.xml", vm_index=index)
    ui_dump = memuc.send_adb_command_vm(command="adb exec-out uiautomator dump /dev/tty", vm_index=index)

And how do you suggest to interact with it? Mainly checking the elements which are present.
