### ISSUE TITLE
Space input issue

### ISSUE THREAD

**Issue by drutkoowski** [pyclashbot/pymemuc#81]
Hi.
I think there is a bug with entering space key.
```
 for char in text_to_type:
        time.sleep(random.uniform(0.01, 0.05))

        if char == '  ':
            adb_command = "shell input keyevent KEYCODE_SPACE" // or 62
        else :       
            adb_command = f"shell input text '{char}'"
            
        status, output = memuc.memuc_run(
            ["-i", str(index), "adb", adb_command], timeout=None
        )
```

and it works for every key but not a space, why? 
Tried with replacing " " with %s as well.

**Comment by martinmiglio** [comment]
This is how I've done it in the past:

```python
# replace spaces with %s
text = text.replace(" ", "%s")
    
pmc.send_adb_command_vm(
   vm_index=vm_index,
   command=f"shell input text {text}",
)
```

Looks like you need to avoid using the single quotes in your call.

**Comment by drutkoowski** [comment]
btw even if I use your solution it still doesnt work with spaces.

**Comment by martinmiglio** [comment]
> Tried everything, I think its a bug, nothing works.

Try executing the ADB command directly with the output generated when using `PyMemuc(debug=true)`. This will narrow down if the bug is caused by `memuc.exe` and its `adb` command, or caused by `PyMemuc` itself.

**Comment by drutkoowski** [comment]
I did run ADB command in debug mode, thats output:
![image](https://github.com/pyclashbot/pymemuc/assets/101982259/10cf919e-1f10-4504-b2bf-261abaf6b396)

code:
```
reformatted_text = "some string".replace(" ", "%s")
    CONTEXT['memuc'].send_adb_command_vm(
        vm_index=CONTEXT['vm_index'],
        command=f"shell input text {reformatted_text}",
    )
```
tried also with:
```
  reformatted_text = "some string".replace(" ", "%s")
    status, output = CONTEXT["memuc"].memuc_run(
        ["-i", str(CONTEXT["vm_index"]), "adb", f'shell input text {reformatted_text}'], timeout=None
    )
```

**Comment by drutkoowski** [comment]
Any updates? There is no way to input a space. Does it work for you?

**Comment by martinmiglio** [comment]
Run the command output by the debug mode in a command prompt. This can tell us if the problem is sourced from `memuc.exe` and the ADB connection, or if it caused by  `pymemuc`.

The method I shared does work in my use cases and runs in a production environment that sees use everyday.

**Comment by drutkoowski** [comment]
I have tried it so many times. Not sure if it's what you meant.
Code:
```
text = text.replace(" ", "%s")
        
    CONTEXT['memuc'].send_adb_command_vm(
    vm_index=CONTEXT['vm_index'],
    command=f"shell input text {text}",
    )
```
![image](https://github.com/pyclashbot/pymemuc/assets/101982259/58859cfd-39aa-404f-84b4-1554c61a982d)

**Comment by martinmiglio** [comment]
execute directly into a command prompt terminal, without using `pymemuc` this:
```cmd
"C:\Program Files\Microvirt\Memu\memuc.exe" -i 1 adb shell input text string%swith%sspaces
```
Here's what happens when I run this:
![image](https://github.com/pyclashbot/pymemuc/assets/10036276/cdd3225f-f6bd-4156-8010-d5ce63dd9717)

**Comment by drutkoowski** [comment]
It says invalid arguments for command text.
So I slightly modified it to: "`.\memuc.exe -i 0 adb shell input text string\ with\ spaces`" which works fine.

**Comment by martinmiglio** [comment]
> Maybe copy and paste to clipboard would work in that case (?)

I think that could be a valid solution.

Which version of android are you using? I've tested it working on the 9.6 image that ships with MEmu.

**Comment by drutkoowski** [comment]
Hmm, not sure. I am using the latest version of Memu.
Could you tell me how to test clipboard solution? Not sure how to do it.

**Comment by martinmiglio** [comment]
> I am using the latest version of Memu

I'd assume you're using android 9, 64 bit. The default of `pymemuc.create_vm` uses this version.



> Could you tell me how to test clipboard solution? Not sure how to do it.

I've not messed with the clipboard operations in adb, but take a look at this: https://stackoverflow.com/questions/37173733/paste-text-on-android-using-adb/39606119#39606119

**Comment by drutkoowski** [comment]
hmm, btw not sure but actually with pymemuc when I run that command: `adb shell input text %s` it doesnt work, but if you paste that in powershell: `.\memuc.exe -i 1 adb shell input text %s` it works fine.
