### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by drutkoowski** [pyclashbot/pymemuc#82]
`RuntimeError: IndexError: list index out of range`

Hello.
Not sure if that a pymemuc related, but I get that error very often, sometimes it works fine (usually) but sometimes it fails without any reason, it happens at different times of the app's runtime.
I am using pyuac with pymemuc.
```
raise RuntimeError(last_line)
RuntimeError: IndexError: list index out of range
```

**Comment by martinmiglio** [comment]
I am unable to determine the cause of this issue with the information you've provided. If you can create a minimal reproduction of the issue then I can look for a root cause.

**Comment by drutkoowski** [comment]
```
@main_requires_admin
def main():
   from pymemuc import PyMemuc

    memuc = PyMemuc(
        memuc_path="./android/memu/MEmu-setup-abroad-sdk-mv.exe", debug=True
    )
   index = memuc.create_vm()
   memuc.start_vm(index)
   installed_apps = memuc.get_app_info_list_vm(index)
   if not ANDROID_APP_NAME in installed_apps:
        memuc.install_apk_vm(
            os.path.join(os.getcwd(), "android/apk/app.apk"),
            index,
            create_shortcut=True,
        )

    memuc.start_app_vm(APP_NAME_SHORT, index)
```

this is how I use it
